name: WeatherForecast_client
description: A sample web application

environment:
  sdk: '>=2.0.1 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0

dependencies:



